### ISSUE TITLE
HA does not update the HMI

### ISSUE THREAD

**Issue by Generalf69** [balloob/home-assistant.io#178]
HA is up and running on my Win10 PC and is showing the HMI in Windows iExplorer.
I am having another HA instance in a Chrome 
[Uploading home-assistant.zip…]()

browser on my Android Tablet 5.0.2

It seems like HA was able to pull data from the ISY, I can see switches and light. For some reason I can not see all of my switches, some are missing.
Anyway, the HMI does not automatically update when
1. switching ON/OFF the light on the actual switch (please note, MobiLinc is updating immediately)
2. switching ON/OFF the light on MobiLinc 

HA is updating its HMI only, when switching on/off from the other HA instance.

I am using the following HW/SW version 
ISY994i with firmware 4.3.26
Win10, Python 3.5.1
HA 0.12.0
MobiLinc 2.0.7

Below the log file after I have ended HA from the command line with CTRL-C

16-01-30 23:03:08 homeassistant.bootstrap: Not initializing discovery because could not install dependency netdisco==0.5.2
16-01-30 23:23:07 homeassistant.core: BusHandler:Exception doing job
Traceback (most recent call last):
  File "c:\users\generalf\appdata\local\programs\python\python35-32\lib\site-packages\homeassistant\core.py", line 826, in job_handler
    func(arg)
  File "c:\users\generalf\appdata\local\programs\python\python35-32\lib\site-packages\homeassistant\core.py", line 299, in onetime_listener
    listener(event)
  File "c:\users\generalf\appdata\local\programs\python\python35-32\lib\site-packages\homeassistant\components\isy994.py", line 99, in stop
    ISY.auto_update = False
  File "C:\Users\generalf\AppData\Roaming\.homeassistant\lib\PyISY\ISY.py", line 122, in auto_update
    self._events.running = val
  File "C:\Users\generalf\AppData\Roaming\.homeassistant\lib\PyISY\Events\events.py", line 114, in running
    self.unsubscribe()
  File "C:\Users\generalf\AppData\Roaming\.homeassistant\lib\PyISY\Events\events.py", line 171, in unsubscribe
    msg = self._mkmsg(strings.unsub_msg)
  File "C:\Users\generalf\AppData\Roaming\.homeassistant\lib\PyISY\Events\events.py", line 50, in _mkmsg
    body = body.format(**self.data)
KeyError: 'sid'

**Comment by rmkraus** [comment]
Please open this issue against the [Home Assistant repository](https://github.com/balloob/home-assistant).

In the meantime, I'll keep trying to find the issue.
