### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by fredrikwe** [balloob/home-assistant.io#251]
C:\Users\fredr>py -m homeassistant --open-ui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\fredr\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\fredr\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
AttributeError: Can't get attribute 'setup_and_run_hass' on <module '__main__' (built-in)>

**Comment by fabaff** [comment]
This is the documentation repository. Please report bug at https://github.com/balloob/home-assistant/issues
